import type { AppProps } from "next/app";
import Head from "next/head";
import { Oxygen } from "@next/font/google";
import { AnimatePresence } from "framer-motion";
import "@/styles/globals.css";
import SignatureFooter from "@/components/SignatureFooter";

const oxygen = Oxygen({ subsets: ["latin"], weight: ["400", "700"] });

export default function App({ Component, pageProps, router }: AppProps) {
  const url = `https://lindman.dev${router.route}`;
  return (
    <>
      <Head>
        <title>Carl Lindman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`flex h-full min-h-screen w-full flex-col items-center justify-start overflow-x-hidden text-white ${oxygen.className}`}
      >
        <AnimatePresence
          mode="wait"
          initial={true}
          onExitComplete={() => window.scrollTo(0, 0)}
        >
          <Component {...pageProps} canonical={url} key={url} />
        </AnimatePresence>
        <div className="flex flex-grow flex-col justify-end">
          <SignatureFooter />
        </div>
      </div>
    </>
  );
}
